apiVersion: clm.cloudnativeapp.io/v1beta1
kind: CRDRelease
metadata:
  name: test-helm
spec:
  version: 1.0.0
  modules:
    - name: nginx.module
      source:
        name: helm-source
        values:
          chartPath: "https://cloudnativeapp.oss-cn-shenzhen.aliyuncs.com/clm/nginx-ingress-0.7.1.tgz"
          namespace: default
          releaseName: nginx